// app/layout.js
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "My App",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        {/*
        Use suppressHydrationWarning here to ignore 
        extension-injected attributes (like Grammarly) 
      */}
        <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        {children}
        </body>
        </html>
    );
}
