// app/layout.js
import "./globals.css";
import { Inter, Manrope } from "next/font/google";
import ToastContainer from "@/components/ToastContainer";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
    title: "My App",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        {/*
        Use suppressHydrationWarning here to ignore 
        extension-injected attributes (like Grammarly) 
      */}
        <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        {children}
        <ToastContainer />
        </body>
        </html>
    );
}
